In [34]:
import numpy
numpy.__version__

'1.22.3'

In [4]:
import numpy as np


version = np.__version__
print(version)

1.22.3


In [32]:
print(result)
result = 0
print(result)

print(result)

4950
0
4950


In [20]:
dd

In [27]:
result = 0
for i in range(1, 101):
    result += i
print(result)

5050


Каждый объект в Python это замаскированная структура языка C, которая содержит не только значение, но и другую информацию.

Например при описании целочисленной  переменной на языке Python, такой как:

In [28]:
x = 10000

представляет собой не просто чистое цедлое число, на самом деле это указатель на составную структуру языка C, содержащую несколько значений.

Переменная состоит из 4 частей:
- счетчик ссылое
- тип переменной
- размер следующих элементов данных
- содержание значения

In [29]:
l = list(range(10))
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [32]:
l2 = [str(c) for c in l]
print(l2)

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


В Python можно создавать массивы определенных типов для более эффективно работающего буфера. Например библиотека array позволяет создавать целочисленные массивы.

In [33]:
import array
l = list(range(10))
a = array.array('i', l)
print(a)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


Тоже самое можно сделать при помощи библиотеки numpy, только она еще позваляет и проводить различные операции с этими масивами.

## Создание массива из списков языка Python

In [34]:
import numpy as np


l1 = np.array([1, 2, 3, 4, 5])
print(l1)

l2 = np.array([3.14, 2, 3, 6])
print(l2)

[1 2 3 4 5]
[3.14 2.   3.   6.  ]


Массив в numpy может быть только с одним типом данных, если их несколько то numpy пытается привести их к одному типу, как в примере 2 выше.

Ключевое слово dtype позволяет четко указать тип данных массива.

In [35]:
l = np.array([1, 2, 3, 4], dtype=float)
print(l)

[1. 2. 3. 4.]


В numpy можно описывать явным образом многомерные массивы. Вложенные списки рассматриваются как строки в итоговом двумерном массиве.

In [37]:
l = np.array([range(i, i+3) for i in [2, 4, 6]])
print(l)

[[2 3 4]
 [4 5 6]
 [6 7 8]]


## Создание массивов с нуля

создание целочисленного массива длины 10 заполненного нулями

In [40]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

создание массива замером 5х3 значиний сс плавающей точкой заполненных единицами

In [41]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

создание массива размером 3х5, заполненный значением 3,14

In [42]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

создаем массив, заполненный линейной последовательностью начинайющийся с 0 и заканчивающийся 20 с шагом 2, аналогично range

In [44]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

создаем массив из пяти значений равномерно располагающихся между 0 и 1

In [46]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

создаем массив 3х3 равномерно распределенных случайных значений от 0 до 1

In [48]:
np.random.random((3, 3))

array([[0.55121224, 0.26239305, 0.49926696],
       [0.44634251, 0.70986143, 0.48792261],
       [0.08128452, 0.53309072, 0.00254466]])

создаем массив размером 3х3 нормально распределенных случайных значений с медианой - и стандартным отклонением 1

In [50]:
np.random.normal(0, 1, (3, 3))

array([[-0.79834757,  0.93438786, -1.92975791],
       [-0.1074372 ,  0.16379745, -0.30276634],
       [-0.66523405,  0.0163417 , -0.42388998]])

создаем массив размером 3х3 слуйных целых чисел в промежутке [0, 10)

In [52]:
np.random.randint(0, 10, (3, 3))

array([[5, 6, 1],
       [6, 3, 9],
       [8, 9, 2]])

создаем единичную матрицу размером 3х3

In [53]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

создаем инициализированный массив из трех целочисленных значений. Значениями будут произвольные, случайно оказавшиеся в соответствующих ячейках памяти данные

In [54]:
np.empty(3)

array([1., 1., 1.])

## Атрибуты массивов библиотеки NumPy

In [58]:
import numpy as np


np.random.seed(0) #начальное значение для целей воспроизводимости

x1 = np.random.randint(10, size=6) #одномерный массив
x2 = np.random.randint(10, size=(3, 4)) #двумерный массив
x3 = np.random.randint(10, size=(3, 4, 5)) #трехмерный массив

# ndim - размерность
# shape - размер каждого измерения
# size - общий размер массива

print("x3 ndim: ", x3.ndim)
print("x3 shpae: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shpae:  (3, 4, 5)
x3 size:  60


In [60]:
# dtype - еще один атрибут типа данных массива
print("dtype: ", x3.dtype)

dtype:  int64


## Индексация массива: доступ к отдельным элементам

In [61]:
x1

array([5, 0, 3, 3, 7, 9])

In [62]:
x1[0]

5

In [63]:
x1[4]

7

In [64]:
x1[-1]

9

In [65]:
x1[-2]

7

Обращение к элементам в многомерном массиве осуществляется через разделенный запятыми кортеж индексов.

In [66]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [68]:
x2[0, 0]

3

In [69]:
x2[2, 0]

1

In [70]:
x2[2, 1]

6

In [71]:
x2[0, 0] = 12

In [72]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

## Срезы массивов: доступ к подмассивам
x[начало: конец: шаг]

### одномерные массивы

In [73]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
x[:5] #первые 5 элементов

array([0, 1, 2, 3, 4])

In [75]:
x[5:] # элементы после индекса 5

array([5, 6, 7, 8, 9])

In [76]:
x[4:7] # подмассив из середины

array([4, 5, 6])

### многомерные подмассивы

In [77]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [78]:
x2[:2, :3] # две строки, три столбца

array([[12,  5,  2],
       [ 7,  6,  8]])

In [79]:
x2[:3, ::2] # все строки, каждый второй столбец

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

Измерения так же можно переворачивать

In [80]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

### Доступ к строкам и столбцам массива

In [81]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [82]:
x2[:, 0]

array([12,  7,  1])

In [83]:
x2[0, :]

array([12,  5,  2,  4])

In [84]:
x2[2]

array([1, 6, 7, 7])

In [87]:
x2_sub = x2[:2, :2]

In [88]:
x2_sub[0, 0] = 99

In [89]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

## Создание копий массива

In [91]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [92]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [93]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## Изменение формы массива

In [96]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [98]:
x = np.array([1, 2, 3])
x.reshape((1, 3))

array([[1, 2, 3]])

In [99]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [100]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [101]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## Слияние и рзабиение массивов

In [103]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [104]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [108]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
# слияние по первой оси координат
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [109]:
# слияние по второй оси координат (с индексом 0)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

Для работы с массивами с различающимися измерениями удобнее и понятнее использовать функции np.vstack (вертикальное объединение) и np.hstack (горизонтальное объединение)

In [111]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])
# объединяет массив по вертикали
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [112]:
# объединяет массив по горизонтали
y = np.array([[99], 
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

## Разбиение массивов

In [122]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
print(x[3: 5])
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[99, 99]
[1 2 3] [99 99] [3 2 1]


N точек раздела это N+1 подмассив

In [124]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [125]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [126]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [136]:
grid = np.arange(12).reshape((3, 4))
print(grid.shape[0])
print(grid.shape[1])

print(grid)

for row in range(grid.shape[0]):
    print(grid[row, :])
    
for col in range(grid.shape[1]):
    print(grid[:, col])

3
4
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


# Выполнение вычислений над массивами библиотеки NumPy: универсальные функции

In [142]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(value):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
print(values)
compute_reciprocals(values)

[6 1 4 4 8]


array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [144]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

9.1 µs ± 68.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## Введение в универсальные функции

In [145]:
print(compute_reciprocals(values))
print(1.0/values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [147]:
np.arange(5)/np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [148]:
x = np.arange(9).reshape((3, 3))
x ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [150]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [152]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


## Сводные покзатели

In [157]:
x = np.arange(1, 6)
# сумма всех элементова массива
np.add.reduce(x)

15

In [159]:
# произведение всех элементов массива
np.multiply.reduce(x)

120

In [161]:
# для сохранения вычислений можно использовать accumulate
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [162]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

## Векторное произведение

In [165]:
# таблица умножения
x = np.arange(1, 10)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

# Агрегирование: минимум, максимум и все, что посередине

## Суммирование значений из массива

In [167]:
import numpy as np

l = np.random.random(100)
sum(l)

50.617288930835684

In [168]:
np.sum(l)

50.6172889308357

In [169]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

52.6 ms ± 145 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
300 µs ± 2.69 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


## Минимум и максимум

In [170]:
min(big_array), max(big_array)

(6.036102300210899e-07, 0.9999969605678884)

In [171]:
np.min(big_array), np.max(big_array)

(6.036102300210899e-07, 0.9999969605678884)

In [173]:
%timeit min(big_array)
%timeit np.min(big_array)

38.5 ms ± 177 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
341 µs ± 6.1 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [174]:
print(big_array.min(), big_array.max(), big_array.sum())

6.036102300210899e-07 0.9999969605678884 499518.71872294566


### Многомерные сводные показатели

In [175]:
M = np.random.random((3, 4))
print(M)

[[0.17847093 0.11357779 0.59874477 0.08731153]
 [0.74518692 0.96774691 0.2851812  0.32593843]
 [0.38510652 0.72678814 0.6428085  0.22501515]]


In [176]:
M.sum()

5.281876772645355

In [177]:
# минимальное значение каждого столбца
M.min(axis=0)

array([0.17847093, 0.11357779, 0.2851812 , 0.08731153])

In [178]:
# минимальное значение каждой строки
M.min(axis=1)

array([0.08731153, 0.2851812 , 0.22501515])

Ключевое слово axis задает измерение массива, которое будет схлопнуто, а не возвращаемое измерение. Так что указание axis=0 означает, что первая ось будет схлопнута: для двумерных массивов значение в каждом из столбцов будут агрегированы.

### ПРИМЕР: чему равен средний рост президентов США

In [179]:
!head -4 data/president_heights.csv

order,name,height(cm)
1,George Washington,189
2,John Adams,170
3,Thomas Jefferson,189


In [180]:
import pandas as pd


data = pd.read_csv('data/president_heights.csv')
heights = np.array(data['height(cm)'])
print(heights)

[189 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
 174 183 183 168 170 178 182 180 183 178 182 188 175 179 183 193 182 183
 177 185 188 188 182 185]


In [ ]:
print