# объекты series библиотеки Pandas

In [1]:
# series это одномерный массив индексированных данных
import pandas as pd
import numpy as np

data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [2]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [3]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [4]:
data[1]

0.5

In [5]:
data[1:3]

1    0.50
2    0.75
dtype: float64

## объект series как обобщенный массив NumPy

In [6]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [7]:
data['b']

0.5

In [8]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=[2, 5, 4, 7])

In [9]:
data

2    0.25
5    0.50
4    0.75
7    1.00
dtype: float64

In [10]:
data[4]

0.75

## объекты series как специализированный словарь

In [21]:
population_dict = {'California': 3832521,
                  'Texas': 2644893,
                  'New York': 19651127,
                  'Florida': 34932135,
                  'Illinois': 23444123}
population = pd.Series(population_dict)
population

California     3832521
Texas          2644893
New York      19651127
Florida       34932135
Illinois      23444123
dtype: int64

In [12]:
population['New York']

19651127

In [14]:
# в отличии от словаря объект Series поддерживает срезы
population['California':'New York']

California     3832521
Texas          2644893
New York      19651127
dtype: int64

## Создание объектов Series

In [15]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

# Объект DataFrame библиотеки Pandas

## DataFrame как обобщенный массив Numpy

Если объект Series аналог одномерного массива, то DataFrame аналог двумерного массива строк и столбцов.

In [17]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297, 'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [22]:
states = pd.DataFrame({'population': population, 'area': area})
states

population    area
California     3832521  423967
Texas          2644893  695662
New York      19651127  141297
Florida       34932135  170312
Illinois      23444123  149995

In [23]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [24]:
states.columns

Index(['population', 'area'], dtype='object')

## Объект DataFrame как специализированный слварь

In [25]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [26]:
states['population']

California     3832521
Texas          2644893
New York      19651127
Florida       34932135
Illinois      23444123
Name: population, dtype: int64

## Создание объектов DataFrame

### Из одного объекта Series

In [29]:
# Объект DataFrame это набор объектов Series.DataFrame состоящих из одного столбца
pd.DataFrame(population, columns=['population'])

population
California     3832521
Texas          2644893
New York      19651127
Florida       34932135
Illinois      23444123

### Из списка словарей

In [31]:
# любой список словарей можно преобразовать в объект DataFrame
data = [{'a': i, 'b': 2 * i} for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [36]:
data = [{'a': 1, 'b': 2}, {'b': 1, 'c': 2}]
pd.DataFrame(data)

a  b    c
0  1.0  2  NaN
1  NaN  1  2.0

### Из словаря объектов Series

In [37]:
pd.DataFrame({'population': population, 'area': area})

population    area
California     3832521  423967
Texas          2644893  695662
New York      19651127  141297
Florida       34932135  170312
Illinois      23444123  149995

### Из двумерного массива NumPy

In [38]:
pd.DataFrame(np.random.rand(3, 2),
            columns=['foo', 'bar'],
            index=['a', 'b', 'c'])

foo       bar
a  0.456878  0.151361
b  0.647737  0.820293
c  0.830456  0.927848

### Из структурированного массива NumPy

In [39]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [40]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

# Объект Index библиотеки Pandas

In [42]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

## Объект Index как неизменяемый массив

In [43]:
ind[1]

3

In [44]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [45]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [46]:
# главное отличие от массивов NumPy это неизменяемость, т.е. их нельзя редактировать по индексам
ind[1] = 0

TypeError: Index does not support mutable operations

## Индекс как упорядоченное множество

In [48]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

indA.intersection(indB) # пересечение

Int64Index([3, 5, 7], dtype='int64')

In [50]:
indA.union(indB)

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [54]:
indA.symmetric_difference(indB)

Int64Index([1, 2, 9, 11], dtype='int64')

# Индексация и выборка данных

## Выборка данных из объекта Series

### объект series как словарь

In [55]:
import pandas as pd
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [56]:
data['b']

0.5

In [57]:
'a' in data

True

In [58]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [59]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [61]:
data['e'] = 1.25

In [62]:
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

### объект series как одномерный массив

In [63]:
# срез посредством явного индекса (последний элемент включается)
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [64]:
# срез посредством неявного целочисленного индекса (последний элемент не включается)
data[0:2]

a    0.25
b    0.50
dtype: float64

In [65]:
# маскирование
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [66]:
# прихотливая индексация (передача массива индексов)
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

### Индексаторы: loc, iloc и ix

при наличии у объекта series явного целочисленного индекса операция индексации data[1] будет использовать явные
индексы, а операция среза data[1:3] неявный индекс.

In [72]:
data = pd.Series(['a', 'b', 'c', 'd', 'e'], index=[1, 3, 5, 7, 9])
data

1    a
3    b
5    c
7    d
9    e
dtype: object

In [71]:
# использование явного индекса при индексации
data[1]

'a'

In [73]:
# использование неявного индекса при срезе
data[1:3]

3    b
5    c
dtype: object

In [74]:
# атрибут loc позволяет выполнять индексацию и срезы с использованием явного индекса
data.loc[1]

'a'

In [75]:
data.loc[1:3]

1    a
3    b
dtype: object

In [76]:
# атрибут iloc выполнить индексацию и срезы, применяя неявный индекс в стиле Python
data.iloc[1]

'b'

In [77]:
data.iloc[1:3]

3    b
5    c
dtype: object

## Выборка данных из объекта DataFrame

### Объект DataFrame как словарь

In [84]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})

data = pd.DataFrame({'area': area, 'pop': pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [80]:
# к отдельным объектам Series составляющим столбцы объекта DataFrame можно обращаться посредством 
# такой же индексации как и для словарей по имени слобца
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [81]:
# можно обращаться к данным и с помощью атрибутов, исползуя в их качестве имена столбцов
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [83]:
data.area is data['area']

True

In [85]:
data.pop is data['pop']

False

In [86]:
data['density'] = data['pop'] / data['area']

In [87]:
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

### Объекты DataFrame как двумерный массив

In [88]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [89]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [90]:
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [91]:
# указание отдельного индекса для массива означает доступ к строке
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [92]:
# указание отдельного индекса для объекта DataFrame доступ к столбцу
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [94]:
data.iloc[:3, :2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [97]:
data.loc[:'Florida', :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860

In [102]:
data.loc[data.index[:3], :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [103]:
data.loc[data.density > 100, ['pop', 'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [104]:
data.iloc[0, 2] = 90

In [105]:
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

### Дополнительный синтаксис для индексации

In [106]:
data['Florida': 'Illinois']

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [107]:
data[1:3]

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [111]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [112]:
data[data.density > 100]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

# Операции над данными в библиотеке Pandas

## Универсальные функции: сохранение индекса

In [116]:
import pandas as pd
import numpy as np

rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [117]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)), columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [118]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [119]:
np.sin(df * np.pi/4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

## Универсальные функции: выравнивание индексов

### Выравнивание индексов в объектах Series

In [120]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [121]:
area.index | population.index

/tmp/ipykernel_369405/3572280633.py:1: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead.
  area.index | population.index


Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [122]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])

In [123]:
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [125]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

### Выравнивание индексов в объектах DataFrame

In [126]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)), columns=list('AB'))
A

A   B
0  1  11
1  5   1

In [128]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)), columns=list('BAC'))
B

B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [129]:
A + B

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [130]:
# stack выстраивает значения объекта А в один столбец
A.stack()

0  A     1
   B    11
1  A     5
   B     1
dtype: int64

In [131]:
fill = A.stack().mean()
A.add(B, fill_value=fill)

A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

## Универсальные функции: выполнение операции между объектами DataFrame и Series

In [133]:
A = rng.randint(10, size=(3, 4))
A

array([[1, 9, 8, 9],
       [4, 1, 3, 6],
       [7, 2, 0, 3]])

In [134]:
A - A[0]

array([[ 0,  0,  0,  0],
       [ 3, -8, -5, -3],
       [ 6, -7, -8, -6]])

In [136]:
# вычитание по строкам
df = pd.DataFrame(A, columns=list('QRST'))
print(df)
df - df.iloc[0]

   Q  R  S  T
0  1  9  8  9
1  4  1  3  6
2  7  2  0  3


Q  R  S  T
0  0  0  0  0
1  3 -8 -5 -3
2  6 -7 -8 -6

In [137]:
# вычитание по столбцам
df.subtract(df['R'], axis=0)

Q  R  S  T
0 -8  0 -1  0
1  3  0  2  5
2  5  0 -2  1

In [138]:
halfrow = df.iloc[0, ::2]
halfrow

Q    1
S    8
Name: 0, dtype: int64

In [139]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1  3.0 NaN -5.0 NaN
2  6.0 NaN -8.0 NaN