In [34]:
import numpy
numpy.__version__

'1.22.3'

In [27]:
result = 0
for i in range(1, 101):
    result += i
print(result)

5050


Каждый объект в Python это замаскированная структура языка C, которая содержит не только значение, но и другую информацию.

Например при описании целочисленной  переменной на языке Python, такой как:

In [28]:
x = 10000

представляет собой не просто чистое цедлое число, на самом деле это указатель на составную структуру языка C, содержащую несколько значений.

Переменная состоит из 4 частей:
- счетчик ссылое
- тип переменной
- размер следующих элементов данных
- содержание значения

In [29]:
l = list(range(10))
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [32]:
l2 = [str(c) for c in l]
print(l2)

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


В Python можно создавать массивы определенных типов для более эффективно работающего буфера. Например библиотека array позволяет создавать целочисленные массивы.

In [33]:
import array
l = list(range(10))
a = array.array('i', l)
print(a)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


Тоже самое можно сделать при помощи библиотеки numpy, только она еще позваляет и проводить различные операции с этими масивами.

## Создание массива из списков языка Python

In [34]:
import numpy as np


l1 = np.array([1, 2, 3, 4, 5])
print(l1)

l2 = np.array([3.14, 2, 3, 6])
print(l2)

[1 2 3 4 5]
[3.14 2.   3.   6.  ]


Массив в numpy может быть только с одним типом данных, если их несколько то numpy пытается привести их к одному типу, как в примере 2 выше.

Ключевое слово dtype позволяет четко указать тип данных массива.

In [35]:
l = np.array([1, 2, 3, 4], dtype=float)
print(l)

[1. 2. 3. 4.]


В numpy можно описывать явным образом многомерные массивы. Вложенные списки рассматриваются как строки в итоговом двумерном массиве.

In [37]:
l = np.array([range(i, i+3) for i in [2, 4, 6]])
print(l)

[[2 3 4]
 [4 5 6]
 [6 7 8]]


## Создание массивов с нуля

создание целочисленного массива длины 10 заполненного нулями

In [40]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

создание массива замером 5х3 значиний сс плавающей точкой заполненных единицами

In [41]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

создание массива размером 3х5, заполненный значением 3,14

In [42]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

создаем массив, заполненный линейной последовательностью начинайющийся с 0 и заканчивающийся 20 с шагом 2, аналогично range

In [44]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

создаем массив из пяти значений равномерно располагающихся между 0 и 1

In [46]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

создаем массив 3х3 равномерно распределенных случайных значений от 0 до 1

In [48]:
np.random.random((3, 3))

array([[0.55121224, 0.26239305, 0.49926696],
       [0.44634251, 0.70986143, 0.48792261],
       [0.08128452, 0.53309072, 0.00254466]])

создаем массив размером 3х3 нормально распределенных случайных значений с медианой - и стандартным отклонением 1

In [50]:
np.random.normal(0, 1, (3, 3))

array([[-0.79834757,  0.93438786, -1.92975791],
       [-0.1074372 ,  0.16379745, -0.30276634],
       [-0.66523405,  0.0163417 , -0.42388998]])

создаем массив размером 3х3 слуйных целых чисел в промежутке [0, 10)

In [52]:
np.random.randint(0, 10, (3, 3))

array([[5, 6, 1],
       [6, 3, 9],
       [8, 9, 2]])

создаем единичную матрицу размером 3х3

In [53]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

создаем инициализированный массив из трех целочисленных значений. Значениями будут произвольные, случайно оказавшиеся в соответствующих ячейках памяти данные

In [54]:
np.empty(3)

array([1., 1., 1.])